### ISSUE TITLE
apostrophes in names

### ISSUE THREAD

**Issue by 3ckdasnk** [TibiaData/tibiadata-api-go#103]
There is problem with nicknames with apostrophes [ **'** ], instead of apostroph there is `\u0026#39;`

The problems found in:

> /v3/guild/...

`{"name":"Alex\u0026#39;Ifrit","title":"","rank":"Member","vocation":"Sorcerer","level":41,"joined":"2022-01-16","status":"offline"}`

not sure, but it might be also in other places where you import names of players, like: 
> /v3/world/... 

 cant really check, cause its hard to find ppl with apostrophe online :joy: 

> /v3/character/...

 might be in killers and reasons like in #97 with nbsp's

**Comment by tobiasehlert** [comment]
nice catch, thanks @3ckdasnk!
I'll check into this during the day :)

**Comment by tobiasehlert** [comment]
@3ckdasnk found the character [Galak'Warrior](https://api.tibiadata.com/v3/character/Galak'Warrior) that was online, so online list works.
Also checked into the house part and it worked as well.

One thing that I could not manage was to find a death with a char that has `'` in it.. might need to search some more hehe
