### ISSUE TITLE
Double quotes faulty in spell formular

### ISSUE THREAD

**Issue by tobiasehlert** [TibiaData/tibiadata-api-go#12]
Need support for double-quotes in spell formula

URL:
https://dev.tibiadata.com/v3/spells/spell/levitate

![image](https://user-images.githubusercontent.com/4417850/147816655-99c787a5-ccbd-43c3-8d58-3e46bbc2c74f.png)

**Comment by darrentaytay** [comment]
@tobiasehlert any preference for how this is handled?

Some possible solutions;

* Escape the double quotes, e.g: `"formula": "exani hur \"up|down\"",`
* Replace double quotes with single quotes, e.g: `"formula": "exani hur 'up|down'",`

**Comment by tobiasehlert** [comment]
> @tobiasehlert any preference for how this is handled?
> 
> 
> 
> Some possible solutions;
> 
> 
> 
> * Escape the double quotes, e.g: `"formula": "exani hur \"up|down\"",`
> 
> * Replace double quotes with single quotes, e.g: `"formula": "exani hur 'up|down'",`
> 
> * No quotes: `"formula": "exani hur up|down",`

Hi @darrentaytay,
I think that the option to run single quotes would be the best option. Would probably look best when considering other spells that have options like remote healing of druids. Or what you think?

**Comment by darrentaytay** [comment]
> > @tobiasehlert any preference for how this is handled?
> > Some possible solutions;
> > 
> > * Escape the double quotes, e.g: `"formula": "exani hur \"up|down\"",`
> > * Replace double quotes with single quotes, e.g: `"formula": "exani hur 'up|down'",`
> > * No quotes: `"formula": "exani hur up|down",`
> 
> Hi @darrentaytay, I think that the option to run single quotes would be the best option. Would probably look best when considering other spells that have options like remote healing of druids. Or what you think?

@tobiasehlert I think that makes sense.

Do you know if this issue is specific to the `formula` or does it appear somewhere else too? 

Not sure whether to just handle it for `formula` or potentially find a more general solution.

**Comment by tobiasehlert** [comment]
> @tobiasehlert I think that makes sense.
> 
> 
> 
> Do you know if this issue is specific to the `formula` or does it appear somewhere else too? 
> 
> 
> 
> Not sure whether to just handle it for `formula` or potentially find a more general solution.

There are some other spells as well. Take a look in https://dev.tibiadata.com/v3/spells to find other spells that are in the same situation. I think it's actually only the _formula_ field that we need to fix.

**Comment by tobiasehlert** [comment]
Closing since spells endpoints are fixed with #14.
