### ISSUE TITLE
Add support for parsing healing elemental damages

### ISSUE THREAD

**Issue by soul4soul** [TibiaData/tibiadata-api-go#176]
Some creatures are healed by elemental damage. tibia library displays this information. 

> What is more, they are healed when fire damage is used against them.

source: https://www.tibia.com/library/?subtopic=creatures&race=lavablob

I would expect this information to be in a [string] field and work the same as immune, strong, and weakness fields

**Comment by tobiasehlert** [comment]
Interesting catch.. is that the only monster healed by anything or are there any other?

**Comment by soul4soul** [comment]
Seems to be the only one from what I can tell so it makes this rather low importance. Yet it would still be nice to have.

**Comment by tobiasehlert** [comment]
@soul4soul ye of course, I just thought that there might be some else so that the parsing can be tested against another creature as well. Even if its one it should be added. I'll check into it on the weekend or so :-)

**Comment by tobiasehlert** [comment]
On.. one more:
https://www.tibia.com/library/?subtopic=creatures&race=foamstalker

**Comment by soul4soul** [comment]
> On.. one more: https://www.tibia.com/library/?subtopic=creatures&race=foamstalker

Wow that is super interesting consider players can't deal agony damage, and last time I was at foamstalkers they don't deal that damage either.
