### ISSUE TITLE
 /v4/character spec and actual response differs

### ISSUE THREAD

**Issue by ivansantos-dev** [TibiaData/tibiadata-api-go#192]
Spec should response should be:
```
{
"character": {
"account_badges": [
{
"description": "string",
"icon_url": "string",
"name": "string"
}],
"account_information": {
"created": "string",
"loyalty_title": "string",
"position": "string"
},
```
Actual response:
```
{
  "character": {
    "character": {
      "name": "Trollefar",
      "sex": "male",
      "title": "Trolltrasher",
      "unlocked_titles": 7,
      "vocation": "Elite Knight",
```

There is an extra object `character` in the actual response.

Also, I noticed some /v4/character broke lookup of some name such as `Crocodilo'Dundee` returns 400 with `"message": "the provided character name has a word too big"`

**Comment by tobiasehlert** [comment]
It is in the correct formation, except that the documentation page renders the data points in the response after alphanumeric but the response is not sorted. You still have the data points you want to look for in the data structure, if they exist for the character you are looking for :-)

Or am I misunderstanding something else you are looking for @ivansantos-dev?

**Comment by ivansantos-dev** [comment]
Sorry, you are correct. I just misread it. I am dumb :( .

I will open another issue instead of tacking it with this one.
