### ISSUE TITLE
/v4/character/{name} fails for certain names

### ISSUE THREAD

**Issue by ivansantos-dev** [TibiaData/tibiadata-api-go#193]
I noticed some /v4/character broke lookup of some name such as Crocodilo'Dundee returns 400 with

```json
{
  "information": {
    "api": {
      "version": 4,
      "release": "edge",
      "commit": "5a7fdbf4da820ab7492c71d1dafeea1b740abaaf"
    },
    "timestamp": "2023-02-19T06:36:26Z",
    "status": {
      "http_code": 400,
      "error": 10006,
      "message": "the provided character name has a word too big"
    }
  }
}
```

The same name works fine with v3

**Comment by tobiasehlert** [comment]
Nice catch thanks! I'll look into this in a couple of hours :-)

**Comment by tobiasehlert** [comment]
Interesting one.. the characters are nowadays only allowed to have a max length of 14 and no `'` in them.
Our validation check is based on the current allowed character-length, so therefore it's failing :)
