### ISSUE TITLE
Characters section, deaths, non-breaking spaces

### ISSUE THREAD

**Issue by 3ckdasnk** [TibiaData/tibiadata-api-go#97]
Im pretty noob at this point, so if its not a bug - sorry.
Well, i rewrite my app to use v3 instead of v2 and after 3 days of using i realized that in every deaths, in every name with "space", instead of normal spaces, there is everywhere non-breaking spaces what literally fucked up everything in my case (for example i cant search for character name, becouse "xxx xxx" its not the same as "xxx\u00a0xxx")
well... i got 10k deaths in my db with that bullshit spaces... **i belive that in v2 there are normal spaces, becouse i never had that problem before**
the problem is with "reasons" and also with all the names separately at deathlist... 
ofc i can fix it by my side while adding everything to db, but im pretty sure it should be changed at api side

**Comment by 3ckdasnk** [comment]
Its definitely a bug, becouse in Worlds online list all player names are with normal spaces, but when it comes to characters deaths every name has nbsp (tibia.com in both places using nbsp, in api only in deathlist its not converted to normal space)

**Comment by tobiasehlert** [comment]
hi @3ckdasnk,

thanks for reporting, to me it seems to work fine now on dev.tibiadata.com
please verify that it looks good for you there too 😃

**Comment by 3ckdasnk** [comment]
@tobiasehlert 

`Crushed at Level 619 by Snake&nbsp;Riddled, Druidaneitor, Mad&nbsp;Dabbin, Waco&nbsp;Feaki, Noraxu, Savage&nbsp;Meche, Gerardo&nbsp;Mcfly, Kielbasa, Sodarock and Kimayri. Assisted by Skkrimz.`

not really :cry: :joy:

**Comment by tobiasehlert** [comment]
Alright @3ckdasnk, I'll look into the reason field too.. thought it was only the name field that gave you issues :)

**Comment by tobiasehlert** [comment]
Hmm..

**Comment by tobiasehlert** [comment]
now it should look better @3ckdasnk. take a look at the dev URL as you mentioned :)

**Comment by tobiasehlert** [comment]
@3ckdasnk released [v3.1.1](https://github.com/TibiaData/tibiadata-api-go/releases/tag/v3.1.1) with the fix and it's also active in on the api. domain :)
Thanks for reporting!
